# Nombre de la aplicación
spring.application.name=GestorTareas

# Conexión a MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/gestorTareas?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.defer-datasource-initialization=true

# JWT Configuration
security.jwt.secret=QWlSZWFsbHlMb25nU2VjcmV0S2V5MTIzNDU2Nzg5MDEyMzQ1Njc4OTA=
security.jwt.ttl-ms=3600000

# Server Configuration
server.port=8080
server.servlet.context-path=/api

# Logging
logging.level.org.springframework.security=INFO
logging.level.org.springframework.web=INFO
logging.level.com.DynorBlue=DEBUG

# Jackson Configuration
spring.jackson.serialization.write-dates-as-timestamps=false